### ISSUE TITLE
active class is applied to outer wrapper.

### ISSUE THREAD

**Issue by cowardcalf** [yahoo/react-stickynode#100]
I guess the value of `activeClass` is supposed to be applied to the inner sticky component, but now they are applying to the out wrapper.

When it is in sticky status, the out wrapper will be scrolled out of the viewport that makes the class on it makes no sense 😢  

Am I right? Or I missed something to use `react-stickynode` properly?

**Comment by rikkit** [comment]
Just target your css to `.active .sticky-inner-wrapper` rather than `.active` (replace "active" with your value of `activeClass` - "active" is the default)

**Comment by cowardcalf** [comment]
> Just target your css to .active .sticky-inner-wrapper rather than .active (replace "active" with your value of activeClass - "active" is the default)

@rikkit Thanks for your suggestion.

I believe definitely that will work. But it looks like  a bypass solution.

I'm wondering what does the `activeClass` do? If it is not assigning class when it is "active".

**Comment by rikkit** [comment]
> Well, I'm guessing the value of activeClass is changing the .active to the value, right?

Correct, I usually set it to `stuck` since I use `active` as a class name for other things.

**Comment by cowardcalf** [comment]
Thanks!
