### ISSUE TITLE
Bundle Size

### ISSUE THREAD

**Issue by MercerK** [yahoo/react-stickynode#1041]
👋 Thanks for creating this package. Looking forward to using it, but the high minified / gzipped sizes are a bit concerning for a single component. It looks like a good portion of it comes from core-js and lodash. Are there any plans to try to reduce the size? 

https://bundlephobia.com/package/react-stickynode@4.2.0

![image](https://github.com/user-attachments/assets/6c5a12d4-b90a-4a7b-b6be-c01b7ce1549e)

**Comment by redonkulus** [comment]
Thanks for the report. The browserlist in the package.json was specifying support for older browsers. I've updated this to only transpiler for modern browsers so this should reduce the size a little:

| Old (CJS/ES) | New (CJS/ES) |
| ------------ | ------------ |
| 22k / 17kb | 21kb / 15kb |

This was released in v5 to avoid breaking any sites still supporting old browsers. https://github.com/yahoo/react-stickynode/releases/tag/v5.0.0

The lodash dependency is pulled in from the subscribe-ui-event package. I can take a look at reducing the dependency footprint there, which would then reduce the size here.

**Comment by redonkulus** [comment]
Ok, I've updated `subscribe-ui-event@v3` to remove lodash, you can see the [bundlephobia change](https://bundlephobia.com/package/subscribe-ui-event@3.0.0) from 29kb / 9kb (gzipped) to 9kb / 3kb (gzipped).

Subsequently, react-stickynode@5.0.1 was further reduced to 17kb min / 6kb (gzipped). That reduced it from 37kb / 11kb (gzipped) on v5.0.0.

**Comment by redonkulus** [comment]
Overall, these packges were created almost 10 years ago based on "modern" code at the time. I'm sure this package could be refactored to remove subscribe-ui-event entirely based on modern APIs. However, there are no plans to do this at this time, if community members would like to contribute, that would be ideal.
