### ISSUE TITLE
Initial sticky state based on scroll position

### ISSUE THREAD

**Issue by benjamindulau** [yahoo/react-stickynode#105]
I have this use case:

```jsx
{hasSelection &&
    <Sticky enabled={true} top={0} bottomBoundary={0} innerZ={999}>
         <BatchEditBar />
    </Sticky>
}
```

The `BatchEditBar` is not visible until at least one item from a list is selected. But when it's visible, it has to be sticky.

It works well if I select an item from list and the scroll is already at the top. I scroll down and the bar gets sticky.

But if I scroll down first, then select an item, the bar appears (due to the hasSelection condition), but it's not sticky by default since at least one scroll event needs to be fired to initiate the sticky state.

Can I force the initial state depending on the current scroll position?

**Comment by hankhsiao** [comment]
Does it work if you hide BatchEditBar only, which means you always activate
sticky but no content inside?

**Comment by benjamindulau** [comment]
Yep, it does work. Seems a bit weird though.

**Comment by rikkit** [comment]
Another workaround is to trigger the scroll handlers after state change - i.e. scroll the window by 1px.

```typescript
this.setState({ hasSelection: true }, () => {
  requestAnimationFrame(
    window.scrollBy(0, 1);
  );
});
```

In my projects I take @hankhsiao 's approach, and hide the contents of the sticky bar using CSS.

**Comment by benjamindulau** [comment]
@rikkit yes that's the first workaround I chose. But still, it would be better that the component take care of this when initializing, maybe by checking the scroll position at that time?

**Comment by collinklippel** [comment]
Is this feature in the works? Like to help out if I can!
