### ISSUE TITLE
String refs warning when using React 16.3 in strict mode

### ISSUE THREAD

**Issue by runmoore** [yahoo/react-stickynode#106]
When using React 16.3 in [strict mode](https://reactjs.org/docs/strict-mode.html), two warnings appear in the console about using string refs. One for the "outer" ref and one for the "inner" ref.

e.g.

> Warning: A string ref, "outer", has been found within a strict mode tree. String refs are a source of potential bugs and should be avoided. We recommend using createRef() instead.

More information on why string refs should be avoided: https://fb.me/react-strict-mode-string-ref

**Comment by redonkulus** [comment]
Fixed by https://github.com/yahoo/react-stickynode/pull/88
