### ISSUE TITLE
The "reset" method does not called correctly.

### ISSUE THREAD

**Issue by kosChupahin** [yahoo/react-stickynode#107]
Good afternoon.
Faced such a problem. I use your component for the sidebar in a large document. The panel itself is fixed in the height of the screen. Sometimes the sidebar moves to the top, I mean, it calls the reset method (looked in your implementation) although the top offset has not been reached.
I can not show this on my page, but I found a case where it is reproduced, though not always.
[example](https://image.ibb.co/eD09D8/sticky_Problem.gif)
The sidebar is a yellow block, it's stickynode.

I started looking at the implementation, and while I'm using a temporary solution.
I replaced it
`if (top <= this.state.topBoundary) { // #1
      this.reset();
    }`
with this
`if (this.state.top < outerRect.top) {
      this.reset();
    }`

I need some clarifications. Why it happens and is my temporary solution bad?

Browsers: 
Chrome Version 66.0.3359.181 (Official Build) (64-bit).
Firefox 60.0.1.

Thank you in advance.

**Comment by redonkulus** [comment]
Please provide a codesandbox to help debug. Re-open if still needed.
