### ISSUE TITLE
Breaks building of a create-react-app application

### ISSUE THREAD

**Issue by koox00** [yahoo/react-stickynode#111]
Updating from `1.4.1` to `2.0.1` breaks the production build of an app created with `create-react-app`.

The error lies in the `subscribe-ui-event` dependency.

```
Failed to minify the code from this file:

        ./node_modules/subscribe-ui-event/dist-es/lib/listen.js:28

Read more here: http://bit.ly/2tRViJ9
```

**Comment by vladserban** [comment]
Same issue. Any fixes? workarounds?

**Comment by redonkulus** [comment]
It looks like `create-react-app` is pulling in the es6 version of the code based on the [`module`](https://github.com/yahoo/subscribe-ui-event/blob/master/package.json#L6) property of the `package.json`. Supposedly this is supported by `create-react-app`

> Note: Create React App can consume both CommonJS and ES modules. For Node.js compatibility, it is recommended that the main entry point is CommonJS. However, they can optionally provide an ES module entry point with the module field in package.json. Note that even if a library provides an ES Modules version, it should still precompile other ES6 features to ES5 if it intends to support older browsers.

It seems to be failing at this part in the `subscribe-event-listener/dist-es/lib/listen.js file:

>   let add = 'addEventListener';

Either way, this is probably a bug for that repository and just a symptom here. It would be better to [open an issue](https://github.com/yahoo/subscribe-ui-event) there.

/cc @roderickhsiao

**Comment by roderickhsiao** [comment]
Will take a look

**Comment by shantp** [comment]
This is not just a create-react-app issue. This broke my webpack build as well and I'm not using create-react-app.

**Comment by roderickhsiao** [comment]
just published subscribe-ui-event@2.0.2

can you guys help to check if that fix the build

**Comment by koox00** [comment]
@roderickhsiao the update fixed the build for me!

**Comment by stefensuhat** [comment]
mine still can't compile with subscribe-ui-event@2.0.2. @koox00 how do you build the project?

**Comment by koox00** [comment]
@stefensuhat my project is created with `create-react-app` the build scripts can be found here https://github.com/facebook/create-react-app/tree/next/packages/react-scripts/scripts

**Comment by kelly-tock** [comment]
sane issue with the latest one here.

**Comment by roderickhsiao** [comment]
Do you guys have a simplified repo that I could checkout and debug?

**Comment by tinder-rhsiao** [comment]
I create a fresh one using `create-react-app` https://github.com/roderickhsiao/debug-create-react-app-es

but I didn't see the compiling error

**Comment by kelly-tock** [comment]
I think there are 2 issues. One was a build one. The other is that since there’s a module field, it lets things like const get through. I think a browser field should also point to main? Older browsers will break like safari 9

**Comment by kelly-tock** [comment]
Oh that’s for subscribe ui event sorry

**Comment by roderickhsiao** [comment]
@kelly-tock all the file loads from `module` fields are transpiled, please try `2.0.3`
