### ISSUE TITLE
Safari having bug when scroll to top

### ISSUE THREAD

**Issue by youwei91** [yahoo/react-stickynode#113]
I met a bug is when in Safari, when I tap to scroll to top, it will leave a huge blank space

![screen shot 2018-06-20 at 2 29 30 pm](https://user-images.githubusercontent.com/11750574/41646154-a4e5d3c0-74a5-11e8-96e5-1bf5dcaae916.png)

After I investigate is due to the _STATUS_FIXED_ is not respond correctly. At Sticky.jsx, line365, the position value should change base on _STATUS_FIXED_ value, but it somehow not changing in Safari when I scrolling fast to top, I try to add another handling _window.pageYOffset_ for it, it fixed the bug. 
` position: this.state.status === STATUS_FIXED && window.pageYOffset ? 'fixed' : 'relative',`
I hope you guys can update it or maybe find another way to fix it, thanks.

**Comment by redonkulus** [comment]
Closing old bugs, please re-open if still an issue on latest Safari.

**Comment by andrickd** [comment]
I can reproduce this issue in Safari 14.1.1 using the most current version (3.1.0 at time of writing) - this issue should be reopened.

**Comment by redonkulus** [comment]
Thanks for spotting, will re-open. Feel free to open a PR to fix if you like.

**Comment by strangeliu** [comment]
Still exist

**Comment by AmmadKhanM** [comment]
still Exist

**Comment by ericmaicon** [comment]
still Exist
