### ISSUE TITLE
Compatibility issues with Google  Chrome v40 and it affects SEO

### ISSUE THREAD

**Issue by vilsad** [yahoo/react-stickynode#116]
Hi,
When I open the site in Google Chrome 40 after using this component, I am getting error Loading chunk 13 failed. Uncaught SyntaxError: Use of const in strict mode. and it fails to render since the js chunk is not loaded. apparently this affects the SEO since Google is using Chrome 40 / 41 to parse the content of the client side rendered pages.

**Comment by redonkulus** [comment]
Chrome 40 is an old browser. What is the reason for using that version?
