### ISSUE TITLE
Sticky No Longet Sticks as of FireFox v62

### ISSUE THREAD

**Issue by pmaddaloni** [yahoo/react-stickynode#117]
While using FF, it appears that the component's state never updates when scrolling a page. I tested this by simply adding a `console.log` to the `onStateChange` function prop. It never prints in the Firefox debug console, and more importantly, it does not stick.

Incidentally, I can get `Sticky` to stick in FF if I scroll down the page, then refresh it. The component is then stuck in place, but is permanently stuck, and never un-sticks (if I scroll back up the page to a place where it should un-stick, it does not).

Both Chrome and Safari still work as expected (and the debug message I added also is printed in the console for both).

**Comment by redonkulus** [comment]
please check latest firefox and let us know if its broken.
