### ISSUE TITLE
Error when testing with jest.

### ISSUE THREAD

**Issue by kchupakhin** [yahoo/react-stickynode#118]
Hello.
I write snapshot test for my component. The **StickyNode**(react-stickynode) is used Inside the renderer method.

In test I've got error:
Error: Uncaught [TypeError: Cannot read property 'getBoundingClientRect' of null] at Sticky.updateInitialDimension

 "jest": "23.5.0"
"react-stickynode": "2.0.1"

**Comment by mohit-pandey** [comment]
Facing similar issue..Did you find any solution?

**Comment by jacktator** [comment]
Hi @kchupakhin , we're facing exact same issue. Did you find a solution for this problem?
