### ISSUE TITLE
bottomBoundary element doesn't update

### ISSUE THREAD

**Issue by remi95** [yahoo/react-stickynode#129]
`<Sticky top={139} bottomBoundary={'#main'}>...</Sticky>`    

I use a simple sticky wrapper with my main element  as _bottomBoundary_.    
The problem is I have many elements loading, and my document height is changing, but the bottomBoundary doesn't recalculate the correct value after that. So my sticky element come over my footer.    

I also tried to pass a **ref** and to use the following method, but nothing :
```js
stickyElement.update();
stickyElement.updateInitialDimension();
stickyElement.updateInitialDimension({ top:139, bottomBoundary:"#main" });
```

Is there a no documented solution ?

**Comment by redonkulus** [comment]
Please provide a codesandbox or demo to help debug and reopen the ticket if still needed.
