### ISSUE TITLE
componentWillReceiveProps does not check props.enabled

### ISSUE THREAD

**Issue by lb-** [yahoo/react-stickynode#131]
## Steps to reproduce
* Disable `Sticky` using the prop `enabled={false}`
* Set up a component to receive other props (either by a re-render by parent) or dynamically changing some other prop on Sticky
* Expectation: Methods like `updateInitialDimension` & `update` are not called due to the component being NOT enabled
* Actual: When disabled, errors occur due to attempts to find the DOM node (or other issues) as the correct setup has not occurred.

## Receiving Error
* Sticky.js:128 Uncaught TypeError: Cannot read property 'value' of null at Sticky.getBottomBoundary (Sticky.js:128) which maps to here https://github.com/yahoo/react-stickynode/blob/e4668b50226b8ebc78fe6ee4ff80d3423497a633/src/Sticky.jsx#L285

```
    componentWillReceiveProps (nextProps) {
        this.updateInitialDimension(nextProps);
        this.update();
    }
```

## Potential Fix
* `componentWillReceiveProps` should check this.props.enabled before continuing and not call         `this.updateInitialDimension(nextProps); this.update();` if enabled is false
* Similar to the checks in `componentDidUpdate` and `componentDidMount`

**Comment by redonkulus** [comment]
Thanks for the issue. Can you provide a code share link so we can see the error?

**Comment by lb-** [comment]
@redonkulus  - I have been able to reproduce with a basic scenario and found that the the steps to reproduce require the bottomBoundary prop to be `null` AND the `<Sticky enabled={false}...`.

But the bottomBoundary prop should not be read when it is disabled.

https://codesandbox.io/s/empty-worker-yuqoc?fontsize=14&hidenavigation=1&theme=dark

In the codesandbox above, first click 'disable sticky', then click 'random name' which will trigger a re-render & props update.

**Comment by redonkulus** [comment]
@lb- do you want to try and provide a fix for this?

**Comment by lb-** [comment]
Sure, I'll give it a try, will ping you if I get stuck. Might not be this weekend though, hopefully soon.

**Comment by lb-** [comment]
@redonkulus when I run `npm run devtest` I get about ten failed tests (full log below) and it fails. I am using Node 10.16.0 and ran a fresh `npm ci` install after checking out the project locally.

Is this expected? What should I be doing differently to ensure I have a valid starting point?

```
❯ npm run devtest

> react-stickynode@3.0.2 devtest /Users/wisdom-like-silence/dev/react-stickynode
> grunt unit

Running "clean:tmp" (clean) task
>> 0 paths cleaned.

Running "clean:dist" (clean) task
>> 1 path cleaned.

Running "babel:unit" (babel) task

Running "babel:dist" (babel) task

Running "shell:mocha" (shell) task


  Sticky
    1) should work as expected (short Sticky)
    ✓ should call the callback on state change
    2) should call the children function on state change
    3) should work as expected (long Sticky)
    4) should work as expected with original postion 20px from top (short Sticky)
    5) should work as expected with original top 20px and 400px bottom boundary (short Sticky)
    6) should not be sticky if bottom boundary is shorter then its height (short Sticky)
    7) should work as expected with selector bottom boundary (short Sticky)
    8) should stick to the top when window resizes larger then Sticky (long Sticky)
    9) should release when height gets changed (long Sticky)
    10) should allow the sticky functionality to be toggled off


  1 passing (105ms)
  10 failing

  1) Sticky
       should work as expected (short Sticky):
     TypeError: Cannot read property 'transform' of undefined
      at checkTransform3d (tmp/tests/unit/Sticky-test.js:110:18)
      at Context.<anonymous> (tmp/tests/unit/Sticky-test.js:136:9)

  2) Sticky
       should call the children function on state change:
     expected stub to not have been called but was called twice
    stub({ status: 0 }) => null at Sticky.render (/Users/wisdom-like-silence/dev/react-stickynode/dist/Sticky.js:446:54)
    stub({ status: 0 }) => null at Sticky.render (/Users/wisdom-like-silence/dev/react-stickynode/dist/Sticky.js:446:54)
  AssertError: expected stub to not have been called but was called twice
      stub({ status: 0 }) => null at Sticky.render (dist/Sticky.js:446:54)
      stub({ status: 0 }) => null at Sticky.render (dist/Sticky.js:446:54)
      at Object.fail (node_modules/sinon/lib/sinon/assert.js:110:29)
      at failAssertion (node_modules/sinon/lib/sinon/assert.js:69:24)
      at Object.assert.(anonymous function) [as notCalled] (node_modules/sinon/lib/sinon/assert.js:94:21)
      at Context.<anonymous> (tmp/tests/unit/Sticky-test.js:178:22)

  3) Sticky
       should work as expected (long Sticky):
     TypeError: Cannot read property 'transform' of undefined
      at checkTransform3d (tmp/tests/unit/Sticky-test.js:110:18)
      at Context.<anonymous> (tmp/tests/unit/Sticky-test.js:200:9)

  4) Sticky
       should work as expected with original postion 20px from top (short Sticky):
     TypeError: Cannot read property 'transform' of undefined
      at checkTransform3d (tmp/tests/unit/Sticky-test.js:110:18)
      at Context.<anonymous> (tmp/tests/unit/Sticky-test.js:248:9)

  5) Sticky
       should work as expected with original top 20px and 400px bottom boundary (short Sticky):
     TypeError: Cannot read property 'transform' of undefined
      at checkTransform3d (tmp/tests/unit/Sticky-test.js:110:18)
      at Context.<anonymous> (tmp/tests/unit/Sticky-test.js:275:9)

  6) Sticky
       should not be sticky if bottom boundary is shorter then its height (short Sticky):
     TypeError: Cannot read property 'transform' of undefined
      at checkTransform3d (tmp/tests/unit/Sticky-test.js:110:18)
      at Context.<anonymous> (tmp/tests/unit/Sticky-test.js:307:9)

  7) Sticky
       should work as expected with selector bottom boundary (short Sticky):
     TypeError: Cannot read property 'transform' of undefined
      at checkTransform3d (tmp/tests/unit/Sticky-test.js:110:18)
      at Context.<anonymous> (tmp/tests/unit/Sticky-test.js:335:9)

  8) Sticky
       should stick to the top when window resizes larger then Sticky (long Sticky):
     TypeError: Cannot read property 'transform' of undefined
      at checkTransform3d (tmp/tests/unit/Sticky-test.js:110:18)
      at Context.<anonymous> (tmp/tests/unit/Sticky-test.js:366:9)

  9) Sticky
       should release when height gets changed (long Sticky):
     TypeError: Cannot read property 'transform' of undefined
      at checkTransform3d (tmp/tests/unit/Sticky-test.js:110:18)
      at Context.<anonymous> (tmp/tests/unit/Sticky-test.js:393:9)

  10) Sticky
       should allow the sticky functionality to be toggled off:
     TypeError: React.createClass is not a function
      at Context.<anonymous> (tmp/tests/unit/Sticky-test.js:427:57)



Warning: Command failed: ./node_modules/mocha/bin/mocha tmp/tests/unit --recursive --reporter spec
 Use --force to continue.

Aborted due to warnings.
npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! react-stickynode@3.0.2 devtest: `grunt unit`
```

**Comment by lb-** [comment]
It appears that `shell:mocha` is run for `npm run devtest` via the gulp task `unit` but not used in the gulp task `cover`. I will assume that I can just use `npm run test` and ignore `npm run devtest` for now (maybe readme needs to be updated).

**Comment by lb-** [comment]
@redonkulus  - upon further investigation, I could not get the functional tests running locally either.

`npm run func` throws an error.

Plus If I intentionally add a failing test to the unit tests or functional tests, `npm run test` will always pass.

I might need a hand getting the dev environment set up for this project as I must be missing something.

I was able to get the unit tests all passing with these changes
https://github.com/lb-/react-stickynode/commit/8b3356819f3f7be14b82e1143fb4cd95fb19a2aa

However, that does not solve the issue of `npm run cover` not appearing to run those tests at all + the `npm run func` not working (I started down the rabbit hole of this and ran into a lot of issues), you can see my attempt at getting the functional tests working here

https://github.com/lb-/react-stickynode/commit/f5fc904a5eabecac2c8337fa038c724c59b9ec95

**Comment by redonkulus** [comment]
Thanks for taking a look at this. I haven’t actually worked in this codebase much. I inherited it via past coworkers. The functional tests haven’t been working for a while, I think we tried to get them working on  saucelabs last year but to no avail. This project needs a lot of TLC to get back into a good testing shape.

**Comment by lb-** [comment]
Ok cool, so I'm not going crazy haha. Do you mind if I submit a PR for the unit tests?

I'll see if I can give another go at the functional ones maybe as a separate PR. Would it be ok if we updated the babel loader to 7 (this is a Dev dependency only).

**Comment by redonkulus** [comment]
Yup tests and updating devDeps is fine by me.

**Comment by redonkulus** [comment]
@lb- I merged a PR (#151) that refactored the tests to use Jest. Do you want to try and provide a fix for the original issue here?

**Comment by lb-** [comment]
Will try to give another go at this on the weekend 👍

**Comment by lb-** [comment]
@redonkulus - so, it appears that this is no longer an issue in the latest master due to the migration to `componentDidUpdate` and some additional checks in `getBottomBoundary`. However, I have a PR that checks this scenario for future so that we can have confidence a similar regression will not happen.

https://github.com/yahoo/react-stickynode/pull/153

**Comment by redonkulus** [comment]
Closed via https://github.com/yahoo/react-stickynode/pull/153
