### ISSUE TITLE
react-stickynode ccrolled slowly to top the sticky is not working

### ISSUE THREAD

**Issue by SajithRAP** [yahoo/react-stickynode#132]
When we scroll top quickly the sticky is removed. But, the issue happens when the page is scrolled top slowly. If we scroll top slow and reached the top of the page then it's not working as intended. Is there a way to fix this. Alternatively, If i could offset the top position i.e, when this should become sticky from top then that may resolve the issue. Thanks.

**Comment by redonkulus** [comment]
Please provide a codesandbox to help debug. Re-open if still needed.
