### ISSUE TITLE
Only a ReactOwner can have refs

### ISSUE THREAD

**Issue by fender** [yahoo/react-stickynode#21]
On older versions of React, we get this error:
```
Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref.
```

Upgrading to React 0.14.7 fixes this. It looks like your module requires the latest React. Perhaps you could either state that in the README or drop the minimum version required?

**Comment by kaesonho** [comment]
hi @fender, thanks for the update,
could you provide some more details? like how do you get this error, is that in the unit test or a real page?

**Comment by fender** [comment]
@kaesonho On a real page where my app already included ReactJS version 0.14.2.

**Comment by hankhsiao** [comment]
It may be because there is a component or a DIV wrapped by Sticky that has `ref` as an attribute. If it is the case, then yes, you need to upgrade to React 0.14

**Comment by fender** [comment]
@hankhsiao This just happened again. To re-create this, you can add these lines to your apps `package.json`:
```
"dependencies": {
  "react": "0.14.7",
  "react-stickynode": "1.0.14"
}
```

Then, when running `npm install` you end up getting both react 0.14.7 and 0.14.8 included as react-stickynode is trying to install the latest react-addons-shallow-compare as a dependency. If we move that to peerDependencies instead, this should be fixed. Note that I use node 0.12.

**Comment by robcolburn** [comment]
Try adding `react-addons-shallow-compare`,  the 14.7 version, as our dependency. Wipe node_modules, and reinstall.

---

Peer dependencies are tricky. They're ignored in npm3, which means npm3 users may not get the addon. Best advice for library is to not use the add on modules.

**Comment by robcolburn** [comment]
Npm, even npm2, should sees that we already have the module that react-sticky depends on

**Comment by fender** [comment]
Thanks @robcolburn. Adding `"react-addons-shallow-compare": "0.14.7"` to my `package.json` fixed it. Closing!

**Comment by drewdrewthis** [comment]
Is there a way to solve this from within react-stickynode without having to explicitly add a new dependency to my `package.json`?
