### ISSUE TITLE
Provide active className for inner wrapper

### ISSUE THREAD

**Issue by kaisian97** [yahoo/react-stickynode#275]
Currenly the activeClass only support for outer-wrapper. 
I need it to support inner wrapper as well.
For example, I want to add box shadow when the sticky is activated.

**Comment by luluhoc** [comment]
bump

**Comment by redonkulus** [comment]
@kaisian97 @luluhoc please feel free to open a PR with this change so we can review it. Thanks!

**Comment by jbthn** [comment]
I can open a PR for this @redonkulus. I don't see a CONTRIBUTING.md, but let me know if there's anything specific I should include. It looks like I'm supposed to put this text
> I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

in my PR... is that saying I've gotten an okay from a repo maintainer, or is that just saying that the changes are my own?

**Comment by redonkulus** [comment]
just follow existing coding style and add a passing test for new functionality. 

I believe the PR template will add that text for you automatically. If it doesn’t, you can add it manually.

**Comment by redonkulus** [comment]
Fixed via https://github.com/yahoo/react-stickynode/pull/461

**Comment by redonkulus** [comment]
Released in react-stickynode@3.1.0 ... thanks for the PR @jbthn!
