### ISSUE TITLE
Add outerStyle.width to prevent wrapper collapsing 

### ISSUE THREAD

**Issue by osym-dh** [yahoo/react-stickynode#37]
Hey, guys!
I wonder whether it's possible to pass sticky width to the outerStyle as it done [here](https://github.com/yahoo/react-stickynode/blob/master/src/Sticky.jsx#L355)? That would prevent wrapper width flickering in case sticky width is larger than wrapper width, i.e. wrapper is stretched by sticky in original state.

**Comment by hankhsiao** [comment]
Outer wrapper is a DIV, it's width is always 100% to its parent. If you want to set its width, you can just set the width of its parent.
