### ISSUE TITLE
Scroll position restoring (e.g. by Gatsby) after page reload doesn’t update sticky position property

### ISSUE THREAD

**Issue by m99coder** [yahoo/react-stickynode#383]
First things first: Thanks for this wonderful plugin 👍 

I’m using the plugin in a Gatsby project. Gatsby automatically restores scroll positions after a reload, but Sticky doesn’t recognize this initial change. Only after I scroll again it updates itself.

**Comment by 7iomka** [comment]
Same issue :(

**Comment by m99coder** [comment]
@7iomka your workaround actually doesn’t work for me, sadly. I tried `useRef` for the `Sticky` element and calling `reset()` a/o `update()` on it. But none of these work. I assume that the internal state is not reflecting reality but blocking an update – even the manual one.

**Comment by 7iomka** [comment]
> @7iomka your workaround actually doesn’t work for me, sadly. I tried `useRef` for the `Sticky` element and calling `reset()` a/o `update()` on it. But none of these work. I assume that the internal state is not reflecting reality but blocking an update – even the manual one.

I agree with you..is bad :(
It broke scroll position after reload.

**Comment by m99coder** [comment]
In the meantime, I did some further research. Exactly these lines (https://github.com/yahoo/react-stickynode/blob/master/src/Sticky.jsx#L175-L182) avoid restoring the state of the sticky element. When I remove every occurrence of `skipNextScrollEvent` it works for the browser back scroll restoration use case.

Nevertheless, it still doesn’t work for the manual reload from a scrolled position though. This check for being disabled (https://github.com/yahoo/react-stickynode/blob/master/src/Sticky.jsx#L201-L203) is evaluated to `true` and even if it would be evaluated to `false`, this second check (https://github.com/yahoo/react-stickynode/blob/master/src/Sticky.jsx#L228) is `false` resulting in a call to `this.fix(0)`, that does not have any effect.

**Comment by AeShevch** [comment]
Same issue

**Comment by redonkulus** [comment]
fixed by https://github.com/yahoo/react-stickynode/pull/409
