### ISSUE TITLE
Demo link?

### ISSUE THREAD

**Issue by oyeanuj** [yahoo/react-stickynode#43]
Hi folks! I was trying to understand different sticky components and couldn't find an example/demo link here. Would it be possible to add one? I'm sure it will help a lot of folks who are interested in such a component! Thank you!

**Comment by src-code** [comment]
Hi @oyeanuj - there's no demo link at this time, though you can see a demo by installing the project and running `grunt functional-debug`.  We could auto-publish this demo to gh-pages at some point though, which I think would be worthwhile to do...

**Comment by oyeanuj** [comment]
@src-code Thanks! +1 for the auto-publish to gh-pages. I think that would be great for anyone perusing through to take a look!
