### ISSUE TITLE
Sticky should sticky to another sticky

### ISSUE THREAD

**Issue by 100kV** [yahoo/react-stickynode#46]
https://github.com/yahoo/react-stickynode/blob/master/src/Sticky.jsx#L292-L294

If the `top` property refers to another `Sticky` instance, it should consider the offset of that `Sticky` instance together with its height.

@hankhsiao

**Comment by 100kV** [comment]
Hi @hankhsiao. I was wondering what you think would be the best way to handle nested `Sticky` instances. Probably instead of only setting the `top` value to be `offsetHeight` of the `topTarget`, it would also add the `style.top` value if it is also stickied.

**Comment by hankhsiao** [comment]
Hi thank you for discussing with me. Let me get back to you lately. I am in
a class.

**Comment by 100kV** [comment]
Hi @hankhsiao. I just wanted to follow up. Is it possible to have this supported? Thanks.

**Comment by hankhsiao** [comment]
I don't understand this scenario. Say A sticky contains B sticky, when A stick to the screen, then B cannot move anymore. So why do you want to set B as sticky, because it cannot move anyway.

**Comment by 100kV** [comment]
Hi @hankhsiao. The scenario I'm indicating does not necessarily refer to Sticky A containing Sticky B. Consider this scenario:

1. Sticky A is a universal header visible across all pages of the site.
2. Sticky B is a secondary header visible to only 1 page of the site.
3. Sticky C is a tertiary header visible in the same page as Sticky B.
4. Sticky A, B, and C have the same height of say `40px`.

So the page can have 3 headers that looks like this:
```
-------------------- Sticky A --------------------
-------------------- Sticky B --------------------
------------------- Sticky C1 -------------------
------------------- Content 1 -------------------
------------------- Sticky C2 -------------------
------------------- Content 2 -------------------
------------------- Sticky C3 -------------------
------------------- Content 3 -------------------
```

I think Sticky B has to be a sticky with `top` referring to Sticky A, and Sticky C should be a sticky with `top` referring to Sticky B. Currently, doing this will have Sticky C overlapping with Sticky B because only the height of Sticky B is considered.

**Comment by hankhsiao** [comment]
Got it, we do calculate it's height https://github.com/yahoo/react-stickynode/blob/master/src/Sticky.jsx#L90 but not offset. Would you mind changing that line a bit and sending PR to us?

**Comment by 100kV** [comment]
Hi @hankhsiao . I recently had bandwidth to work on this. Here is the diff of a fix I had in mind:

```
@@ -61,10 +61,6 @@ class Sticky extends Component {
         };
     }

-    getTargetHeight (target) {
-        return target && target.offsetHeight || 0;
-    }
-
     getTopPosition (top) {
         // TODO, topTarget is for current layout, may remove
         // a top argument can be provided to override reading from the props
@@ -73,11 +69,20 @@ class Sticky extends Component {
             if (!this.topTarget) {
                 this.topTarget = doc.querySelector(top);
             }
-            top = this.getTargetHeight(this.topTarget);
+            top = this.getTargetTop(this.topTarget);
         }
         return top;
     }

+    getTargetTop (target) {
+        if (!target) {
+            return 0;
+        }
+        var rect = target.getBoundingClientRect();
+        return rect.bottom;
+    }
+
     getTargetBottom (target) {
         if (!target) {
             return -1;
```

The above change seems to work correctly, aside for the case where I scroll down and the target sticky is not fixed yet. It works correctly when I scroll up. It also works correctly when I scroll down past the point where the target sticky is fixed. I think I am missing some information. Also, could you clarify on the line you linked to? I don't understand how the `bottomBoundary` plays into this. Thanks.

**Comment by hankhsiao** [comment]
The `Element.getBoundingClientRect()` method returns the size of an element and its position relative to the viewport. That means, `rect.bottom` could be negative when you scroll to the middle of the page.

https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect

**Comment by raoulus** [comment]
I would love to get this functionality.

@100kV @hankhsiao 
Couldn't we just add the offset to height?
```
getTargetHeight (target) {
  return target && (target.offsetHeight + target.getBoundingClientRect().top) || 0;
}
```

Thoughts?

**Comment by redonkulus** [comment]
Closing old bugs, please re-open if still needed.
