### ISSUE TITLE
Elastic scrolling breaks sticky

### ISSUE THREAD

**Issue by timothyarmes** [yahoo/react-stickynode#50]
Hi,

Stickies are working perfectly for me on Chrome and Firefox.

On Safari it seems that the elastic scrolling breaks the Sticky. Once I reach the top/bottom and see the elastic effect I have to scroll twice in the opposite direction to get it scrolling again.

This is on Safari for Mac.

Tim

**Comment by hankhsiao** [comment]
Thank you, I will test it later. But we should have test on safari, if you
can provide me more information or the testing page, that will be so
useful. Thank you for reporting.

**Comment by vadimgoncharov** [comment]
@timothyarmes @hankhsiao guys, do you have any movements on this issue?

**Comment by vadimgoncharov** [comment]
If we use `enableTransforms={false}`, everything works fine. I think it's may related to `transform` property.

**Comment by redonkulus** [comment]
Closing old bugs, please re-open if still needed.
