### ISSUE TITLE
Empty package in npm

### ISSUE THREAD

**Issue by krvital** [yahoo/react-stickynode#52]
I'm trying to install react-stickynode and gets package with no dist folder. [screenshot](https://yadi.sk/i/Dds08WzQtw8Pq)

**Comment by osym-dh** [comment]
The same issue. Reproduced after switching to v1.2.0

**Comment by redonkulus** [comment]
@krvital @osym-dh fixed in version 1.2.1

**Comment by nason** [comment]
Confirmed, it's all good now. Thanks @redonkulus!
