### ISSUE TITLE
Stick to `parentNode`

### ISSUE THREAD

**Issue by ha404** [yahoo/react-stickynode#55]
Can there be an option for this to stick to the parent element? I would find it extremely convenient if I didn't have to specify the `bottomBoundary` manually.

**Comment by emwee** [comment]
👍 +1

**Comment by webyonet** [comment]
+1

**Comment by hankhsiao** [comment]
Ideally, it should set it's parent as boundary. But, in most case, it's
parent is collapsed, and users get confused that sticky node doesn't work.
So explicitly set the bottomBoundary could be a better solution to educate
people. I agree it will be more convenient, but introducing another prop
will also confuse people.
