### ISSUE TITLE
Can not import library in codepen

### ISSUE THREAD

**Issue by LeComptoirDesPharmacies** [yahoo/react-stickynode#551]
Hi everyone,

I would like to create an issue with a codepen but as soon as I add import to "react-stickynode" in a codepen, it broke the compilation.
Is there any workaround to get "Sticky" working in a codepen ?

Ex : https://codesandbox.io/s/adoring-meninsky-jz2jz?file=/src/App.js

Yours faithfully,
LCDP

**Comment by redonkulus** [comment]
Thanks for the report. So I tried your link and you are correct, it seems the import is not working properly there. I'm not sure why, if I change the `import` to old fashioned `require` then it works fine. Its either how codesandbox handles imports or that we are not publishing es modules with react-stickynode. I can fix the package to also export that to see if that helps.

**Comment by redonkulus** [comment]
@LeComptoirDesPharmacies I just published v4.0.0 which also includes es modules in the package. Try that out in the codesandbox and let me know if that helps.

**Comment by stu01509** [comment]
Seems like this issue has been resolved, maybe we could close the issue.
