### ISSUE TITLE
Target element disregards `bottomBoundary` padding

### ISSUE THREAD

**Issue by ha404** [yahoo/react-stickynode#56]
Perhaps there should be an option to account for the `bottomBoundary` element's padding?

![screen shot 2016-08-10 at 5 54 19 pm](https://cloud.githubusercontent.com/assets/567126/17576033/a456d060-5f23-11e6-8966-f6538401facf.png)

**Comment by hankhsiao** [comment]
You may see the problem as well, which is it's too many cases we want the
bottom target to be. Maybe what we can do is to introduce alignment, so you
can assign boundary target to your parent but align to its bottom.

**Comment by mariomc** [comment]
Are you using box-sizing: border-box ? That makes it so the padding counts for the element's height. Try it out
