### ISSUE TITLE
Providing a selector AND an offset for top prop

### ISSUE THREAD

**Issue by soutar** [yahoo/react-stickynode#58]
Would you consider adding support for specifying a selector **and** an offset? I think it would be useful for declaring an amount of "distance" that a sticky element should keep from the selected element.

The change could be non-breaking and could looking something like:

```js
<Sticky top={ ['#header', 12] }></Sticky>
```

or

```js
<Sticky top='#header' offsetFromTopSelector={12}></Sticky>
```

If you would be okay with this change then I'm happy to submit a PR.

**Comment by jakewisse** [comment]
I was just looking into this, but it doesn't look possible without breaking from `subscribe-ui-event` or modifying its functionality. (This is the lib that react-stickynode uses for [attaching scroll event listeners](https://github.com/yahoo/react-stickynode/blob/master/src/Sticky.jsx#L346).) They've got their `scroll` subscriptions [hardcoded to the `window`.](https://github.com/yahoo/subscribe-ui-event/blob/master/src/mainEventConnectors.js#L190)
