### ISSUE TITLE
How  stay sticky on reload page?

### ISSUE THREAD

**Issue by zjoin** [yahoo/react-stickynode#61]

**Comment by allanpope** [comment]
I've got the same issue. If I scroll down the page so the element is in a sticky state and then refresh the page, the element is not sticky. It becomes sticky if I start scrolling again. @zjoin my current work around is to dispatch a window resize event on page load.

**Comment by MilllerTime** [comment]
Triggering either a resize or a scroll event once the DOM is ready does the trick.
