### ISSUE TITLE
body { overflow-x: hidden; } breaks sticky on Firefox

### ISSUE THREAD

**Issue by yongzhihuang** [yahoo/react-stickynode#64]
Hi, I am seeing an issue where if I have 
```
body {
  overflow-x: hidden;
}
```
rule applied, the sticky does not work on Firefox (52.0.2 (64-bit)) on OSX Yosemite.

**Comment by scottwarren** [comment]
Hey @yongzhihuang it'd be good to get a [Codepen](codepen.io) with an example of this happening (even if it's just including the library and adding the `body { overflow-x: hidden; }` CSS. Just makes it easier to test things out with the codebase when there is a simple example of the code breaking :)

**Comment by anthonyLukes** [comment]
I have a similar issue https://codesandbox.io/s/2o7wvnmkvn. In my case the body/window doesn't scroll and instead a child element is scrolling. I'm guessing `subscribe('scroll', ... );` only applies to the window.

**Comment by redonkulus** [comment]
@anthonyLukes @yongzhihuang please feel free to open a PR to fix or close if not an issue anymore.
