### ISSUE TITLE
breakConfig option in .babelrc file breaks webpack build when the parent version of Babel is 6

### ISSUE THREAD

**Issue by zutler** [yahoo/react-stickynode#67]
node_modules/react-stickynode/.babelrc.breakConfig - This is not a necessary option in Babel 6

**Comment by redonkulus** [comment]
This is odd, the .babelrc doesn't need to be published anyways. I will take a look.

**Comment by redonkulus** [comment]
@zutler I published a new package, react-stickynode@1.3.1, that does not include the .babelrc file.

**Comment by zutler** [comment]
@redonkulus thanks for a quick resolution.  However, I only see one file changes:
https://github.com/yahoo/react-stickynode/commit/446c565d594e3d540d4facbbfb50819ed69fda07#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

and .babelrc file is still there with the same content.

**Comment by zutler** [comment]
Thank you!
