### ISSUE TITLE
Flicker when transitioning to active

### ISSUE THREAD

**Issue by jon-node28** [yahoo/react-stickynode#69]
With a Sticky container that is 1px from being active on page load, the transition from inactive to active causes the content to flicker, jumping up until height value is set to correct it's position.

**Comment by alolis** [comment]
I am noticing the same behavior

**Comment by flyingsky** [comment]
I add some padding bottom on the container to solve this problem.

**Comment by redonkulus** [comment]
Please provide a codesandbox to help debug. Re-open if still needed.
