### ISSUE TITLE
Force a recalculation of height values based on window

### ISSUE THREAD

**Issue by spirift** [yahoo/react-stickynode#76]
I have a situation when I use `react-stickynode` for a sidebar and the page body can change height based on user input to filter away results. When the page body becomes smaller than the window it can cause some pretty weird behavior where the scroll position of the window will jump around and the sidebar flashes on and off the screen.
A simple fix for this is to unmount and then mount the Sticky component again. I can see that some calculations are done in the `componentWillMount` life-cycle method. What I would really like is a way to force these calculations to run again. Unless I am missing something that would cause an issue here?

**Comment by rikkit** [comment]
I think I see this issue as well, when the document shortening for whatever reason causes the sticky element to be positioned below its bottom threshold. It's corrected on scroll, so a workaround is to do just scroll the window 1px up or down when you know it's changed.

**Comment by spirift** [comment]
Yes that's true, I will give that a try and let you know how it works out.

**Comment by spirift** [comment]
I used `window.scrollBy(0, -1)` to no avail. I also tried with 100px and still no luck though the problem isn't as pronounced. Using `window.scrollTo(0, 0)` works and is possibly a better solution than unmounting and mounting again. I also tried putting the `scrollBy` in a `setTimeout` to make sure it was calculated last but this didn't have much effect.

**Comment by ryan-ajmadison** [comment]
Does anyone have a good solution for this? I really like this package, but this is a common bug for me and I need a better solution to this issue.
