### ISSUE TITLE
Sticky thead

### ISSUE THREAD

**Issue by liubko** [yahoo/react-stickynode#78]
`validateDOMNesting` error when using inside `<table>`

**Comment by rikkit** [comment]
This is an warning from React. table elements are only allowed to contain some elements according to the HTML spec https://developer.mozilla.org/en/docs/Web/HTML/Element/table

To create a sticky thead using this component that is also valid html, you need to get creative. In my app I have a separate table with the same column headers as the table with data in it. The separate table is wrapped with react-stickynode and is positioned over the data table using CSS. Column widths are then updated on component mount and component resize.

Example structure

```
<div>
  <Sticky>
    <table>
       <thead>
         <tr>
           {columns.map(x => <td>{x}</td>)}
         </tr>
       </thead>
     <table>
  </Sticky>

  <table>
    <thead>
       <tr>
         {columns.map(x => <td>{x}</td>)}
       </tr>
    </thead>
    <tbody>
       <!-- cell data -->
     </tbody>
</div>
```

You might prefer to use another package than rolling your own though.
