### ISSUE TITLE
glitch when scrolling

### ISSUE THREAD

**Issue by isaacalves** [yahoo/react-stickynode#79]
I have a very simple implementation of react-sticky node:

```
<Sticky
  innerZ={ 1000 }
  activeClass='sticky-header'
>
  <Header
   //...
  />
</Sticky>
```
and in my Sass file:

```
.sticky-header {
	.header {
		// styles that make the header shorter
	}
}
```
This is the initial state of the Sticky, when the header is not Sticky:

![screenshot 2017-08-11 11 13 53-1](https://user-images.githubusercontent.com/1765942/29209510-ccf4bcd4-7e86-11e7-930d-5cd541ee580a.png)

When I drag the scrollbar down, as soon as the Header reaches the top of the viewport, it will get the `sticky-header` class and the status will be "2". _The **bottom** and **height** will be unchanged though and there will be a unwanted space between the fixed header and the content below:_

![screenshot 2017-08-11 11 12 57-2](https://user-images.githubusercontent.com/1765942/29209537-04267a12-7e87-11e7-9814-f32dadc98a2b.png)

After this point, if I continue to scroll down the page, just a tiny bit, the bottom and height will change from 442 to 196 (from the non-sticky header height to the sticky header height) and the content below will jump up just below the Header (where it should be):

![screenshot 2017-08-11 11 14 15-3](https://user-images.githubusercontent.com/1765942/29209560-21bec390-7e87-11e7-81e0-617ec035e815.png)

It seems that there are two events firing separately: the first one adds the `sticky-header` class but adds the height of the non-sticky header to it, thus creating this gap. The second one corrects it, adding the actual height of the Header on its sticky state.

**Comment by isaacalves** [comment]
This workaround kind of solves it, but it still doesn't play well with a 'scroll to anchor' feature I'm painfully trying to put together

```
onStickyStateChange(e) {
    if (header){
      if (e.status === Sticky.STATUS_FIXED) {
        header.style.height = 199  + 'px';
      }else{
        header.style.height = 442 + 'px';
      }
    }
}
```

**Comment by CWolfs** [comment]
Thanks - this helped me out
