### ISSUE TITLE
Jumpy behavior bug

### ISSUE THREAD

**Issue by itwasmattgregg** [yahoo/react-stickynode#80]
Anyone else seeing jumpy behavior of sticky element right after it becomes sticky? Any ideas how to fix this?

**Comment by rikkit** [comment]
This'll be because of the transition of the outer container to ```position: fixed```. Basically you need to avoid applying height affecting CSS to the outer container, and only to ```.sticky-inner-wrapper``` so that the height maths are consistent between stuck and unstuck modes.

**Comment by MurhafSousli** [comment]
I also have the same behavior on edge, but it works properly on chrome and firefox

**Comment by redonkulus** [comment]
Please open a codersandbox example to help debug, re-open if still needed.
