### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by testerez** [yahoo/react-stickynode#9]
Hi,
I'm using this component on the right column of a responsive app.
Obviously, in mobile mode, I won't have columns anymore and would like to disable the sticky behaviour.
How do you suggest to handle the common case?

**Comment by testerez** [comment]
Right now, I do it by css:
```
@media (max-width:$screen-md){
  .sticky-inner-wrapper {
    position: static!important;
    transform: none !important;
    width: auto !important;
  }
}
```

**Comment by hankhsiao** [comment]
You can disable sticky by passing "enabled: false" and hide it with CSS.

**Comment by hankhsiao** [comment]
@testerez, did my suggestion help you?

**Comment by testerez** [comment]
@hankhsiao it would have needed to keep my JS in sync with my CSS media queries. So I sticked to the [CSS solution](https://github.com/yahoo/react-stickynode/issues/9#issuecomment-173039715)

**Comment by timothyarmes** [comment]
For those using Tailwind, a nice solution is something like this:

```
        <Sticky
          top={40}
          innerActiveClass="max-lg:!static max-lg:!transform-none max-lg:!w-auto"
        >
```

The classes applied the active inner div will disable the stick behaviour below the lg breakpoint.
