### ISSUE TITLE
Sticky dissapears with scrollIntoView

### ISSUE THREAD

**Issue by aivanov93** [yahoo/react-stickynode#91]
Hi!
I have two sticky components on my page, a sticky header and a sticky sidebar.
```
<Sticky>
  <Header />
</Sticky> 
<ColumnRow>
  <Column>
    <Sticky>
      <Sidebar />
    </Sticky>
  </Column>
  <Column>
    <Content />
  </Column>
</ColumnRow>
```
The sidebar links to different sections in the content using hash links.
The problem I have is as follows: sometimes (I haven't exactly figured out when) jumping to a section causes the sidebar to disappear. The header never disappears though and I assume the issue is because the sidebar is taller than the viewport. You always have to scroll up or down a little to make it appear.
Logging the state change revealed that in cases when it disappears it gets released right after calling `element.scrollIntoView()`. I have tried firing resize events, scrolling a pixel down, nothing totally fixes it.

**Comment by redonkulus** [comment]
Please provide a codesandbox to help debug. Re-open if still needed.
