### ISSUE TITLE
Fork/rename this project

### ISSUE THREAD

**Issue by src-code** [yahoo/react-stickynode#95]
Currently there's no one within Yahoo/Oath that has a desire to continue maintaining this project, so it'd be great if someone were to step forward and fork/rename this project and maintain it going forward so we can archive this repo.  

Anyone willing?

cc @hankhsiao @roderickhsiao @markwoon @kunukn @aclimatt @redonkulus

**Comment by roderickhsiao** [comment]
I will ping @hankhsiao to see if he want to maintain as he is the original owner

**Comment by hankhsiao** [comment]
I am willing to maintain. How can I do that?

**Comment by redonkulus** [comment]
@hankhsiao really just need to ensure that you follow up on issues/PRs, test new features and publish. Same old stuff. Just need to make sure its up to date.

**Comment by roderickhsiao** [comment]
@redonkulus I think @hankhsiao is asking the process. Forking this into his repo?

**Comment by redonkulus** [comment]
Can leave it, I don't think it has to move. Unless @src-code has a reason.

**Comment by roderickhsiao** [comment]
> so it'd be great if someone were to step forward and fork/rename this project and maintain it going forward so we can archive this repo.

:)

**Comment by redonkulus** [comment]
That's fine too.

**Comment by roderickhsiao** [comment]
So I fork this repo https://github.com/roderickhsiao/react-stickynode, I can take the ownership if you guys want to archive this repo :) 

Also, is this package still used in the company? Or is it okay to do major refactor and bump to version (revisit some logic that we added before to handle edge cases)

**Comment by redonkulus** [comment]
We still use it internally. I'm fine with a refactor and major version bumping it.

**Comment by roderickhsiao** [comment]
okay Sir, will spend sometime take a look
