### ISSUE TITLE
Horizontal Scrolling issue

### ISSUE THREAD

**Issue by Benjiman1986** [yahoo/react-stickynode#96]
I have two parts content on one page, when scrolling down, the left part will be presented as sticky style. When the left part is sticky, if there is a horizontal scroll bar on the page, if dragging the horizontal scroll, the sticky left part content still be shown on the same place of the page, which make the website looks strange. Is there a way to solve this issue?

![image 1](https://user-images.githubusercontent.com/19341353/32594400-daf11d60-c566-11e7-9dc6-2c7fa1443a41.png)

**Comment by alexpriceonline** [comment]
I'm having the same issue. Not sure what happening!

**Comment by alexpriceonline** [comment]
Never-mind... It was an issue with some unrelated CSS

**Comment by Benjiman1986** [comment]
Finally I fix this issue by auto changing the "left" style of the sticky node while horizontal scrolling

**Comment by charkour** [comment]
@Benjiman1986, how did you auto change the "left" style while horizontal scrolling?
